before_script:
  - apt-get update -qq
  - apt-get install -y python python3 python-dev python3-dev
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install -r dev-requirements.txt

python2:
  script:
    - tox -e py27-flake8_2.5,py27-flake8_2.6,py27-flake8_3

python3:
  script:
    - tox --skip-missing-interpreters -e py34-flake8_2.5,py34-flake8_2.6,py34-flake8_3,py35-flake8_2.5,py35-flake8_2.6,py35-flake8_3

linters:
  script:
    - tox -e linters
